#!/bin/bash

# 服务器端部署命令集合
# 在本地执行这些命令来准备服务器部署

SERVER_IP="106.54.44.45"
SERVER_PASS="qwsdcv123!@#"
PROJECT_DIR="/root/ai-project-mgmt"

echo "=== 服务器部署命令 ==="
echo "请在服务器上依次执行以下命令："
echo ""
echo "1. SSH登录服务器："
echo "ssh root@$SERVER_IP"
echo "密码: $SERVER_PASS"
echo ""
echo "2. 更新系统并安装工具："
echo "apt-get update && apt-get install -y curl wget unzip git"
echo ""
echo "3. 安装Docker："
echo "curl -fsSL https://get.docker.com -o get-docker.sh"
echo "sh get-docker.sh"
echo "systemctl enable docker"
echo "systemctl start docker"
echo ""
echo "4. 安装Docker Compose："
echo "curl -L 'https://github.com/docker/compose/releases/v2.21.0/download/docker-compose-$(uname -s)-$(uname -m)' -o /usr/local/bin/docker-compose"
echo "chmod +x /usr/local/bin/docker-compose"
echo ""
echo "5. 创建项目目录："
echo "mkdir -p $PROJECT_DIR"
echo "cd $PROJECT_DIR"
echo ""
echo "6. 下载项目（使用wget从GitHub或其他方式）："
echo "# 方案A: 如果你有代码仓库"
echo "git clone <your-repo-url> ."
echo ""
echo "# 方案B: 使用本地上传的tar文件（如果之前上传了）"
echo "ls -la /tmp/project.tar.gz && tar -xzf /tmp/project.tar.gz"
echo ""
echo "7. 配置环境文件："
echo "cp .env.prod.example backend/.env"
echo "nano backend/.env  # 编辑配置"
echo ""
echo "8. 构建和启动："
echo "docker-compose -f docker-compose.prod.yml build"
echo "docker-compose -f docker-compose.prod.yml up -d"
echo ""
echo "9. 查看状态："
echo "docker-compose -f docker-compose.prod.yml ps"